# Generated by Django 4.2.7 on 2023-11-19 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vpn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='data_volume',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='site',
            name='transitions_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='site',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to=settings.AUTH_USER_MODEL),
        ),
    ]
